/* This file was autogenerated by openCONFIGURATOR-1.4.1 on 11-Apr-2016 17:16:30 */
#ifndef XAP_h
#define XAP_h

# define COMPUTED_PI_OUT_SIZE 12
typedef struct
{
	unsigned CN1_M00_X20PS9400a_NetworkStatus:8;
	unsigned CN1_M00_X20PS9400a_StatusInput01:1;
	unsigned CN1_M00_X20PS9400a_Bit_Unused_01:1;
	unsigned CN1_M00_X20PS9400a_StatusInput02:1;
	unsigned CN1_M00_X20PS9400a_Bit_Unused_02:5;
	unsigned CN1_M01_X20DI9371_NetworkStatus:8;
	unsigned PADDING_VAR_1:8;
	unsigned CN1_M01_X20DI9371_DigitalInput:16;
	unsigned CN1_M02_X20DO9322_NetworkStatus:8;
	unsigned PADDING_VAR_2:8;
	unsigned CN1_M02_X20DO9322_StatusInput01:16;
	unsigned PADDING_VAR_3:16;
} PI_OUT;

# define COMPUTED_PI_IN_SIZE 4
typedef struct
{
	unsigned CN1_M02_X20DO9322_DigitalOutput:16;
	unsigned CN2_M01_Cross_Traf_B1:16;
} PI_IN;

#endif
